spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/db_even_first_3
    username: even_first_3
    password: loctite

mybatis:
  mapper-locations: mappers/**/*.xml


springdoc:
  swagger-ui:
    path: /swagger.html
server:
  port: 8080

